# Python stubs generated by omniidl from ChatApp.idl
# DO NOT EDIT THIS FILE!

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA


_omnipy.checkVersion(4,2, __file__, 1)

try:
    property
except NameError:
    def property(*args):
        return None


#
# Start of module "ChatApp"
#
__name__ = "ChatApp"
_0_ChatApp = omniORB.openModule("ChatApp", r"ChatApp.idl")
_0_ChatApp__POA = omniORB.openModule("ChatApp__POA", r"ChatApp.idl")


# interface ChatServer
_0_ChatApp._d_ChatServer = (omniORB.tcInternal.tv_objref, "IDL:ChatApp/ChatServer:1.0", "ChatServer")
omniORB.typeMapping["IDL:ChatApp/ChatServer:1.0"] = _0_ChatApp._d_ChatServer
_0_ChatApp.ChatServer = omniORB.newEmptyClass()
class ChatServer :
    _NP_RepositoryId = _0_ChatApp._d_ChatServer[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_ChatApp.ChatServer = ChatServer
_0_ChatApp._tc_ChatServer = omniORB.tcInternal.createTypeCode(_0_ChatApp._d_ChatServer)
omniORB.registerType(ChatServer._NP_RepositoryId, _0_ChatApp._d_ChatServer, _0_ChatApp._tc_ChatServer)

# ChatServer operations and attributes
ChatServer._d_sendMessage = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), (), None)

# ChatServer object reference
class _objref_ChatServer (CORBA.Object):
    _NP_RepositoryId = ChatServer._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def sendMessage(self, *args):
        return self._obj.invoke("sendMessage", _0_ChatApp.ChatServer._d_sendMessage, args)

omniORB.registerObjref(ChatServer._NP_RepositoryId, _objref_ChatServer)
_0_ChatApp._objref_ChatServer = _objref_ChatServer
del ChatServer, _objref_ChatServer

# ChatServer skeleton
__name__ = "ChatApp__POA"
class ChatServer (PortableServer.Servant):
    _NP_RepositoryId = _0_ChatApp.ChatServer._NP_RepositoryId


    _omni_op_d = {"sendMessage": _0_ChatApp.ChatServer._d_sendMessage}

ChatServer._omni_skeleton = ChatServer
_0_ChatApp__POA.ChatServer = ChatServer
omniORB.registerSkeleton(ChatServer._NP_RepositoryId, ChatServer)
del ChatServer
__name__ = "ChatApp"

#
# End of module "ChatApp"
#
__name__ = "ChatApp_idl"

_exported_modules = ( "ChatApp", )

# The end.
